# 서버
server:
  port: 8093

#DB 접속 정보
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: boardproject
    password: 1234
  thymeleaf:
    cache: false

    #JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # mysql의 엔진을 쓴다 라는 개념.
    show-sql: true
    hibernate:
      ddl-auto: update
