# 서버
server:
  port: 8092

# DB 접속 정보
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql 쓰기 위해서 명명 하는 것.
    url: jdbc:mysql://localhost:3306/springbootclass?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #                           host 데이터베이스               기준시간                       인코딩   UTF-8
    username: bootuser
    password: 1234
  thymeleaf:
    cache: false # 캐쉬를 누적하지 않는다 라는 뜻.

  # JPA 관련 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # mysql의 엔진을 쓴다 라는 개념.
    show-sql: true
    hibernate:
      ddl-auto: update # ?? 이게 뭔데? ddl : data definition language?

# mybatis 관련 설정 (만약 사용할꺼라면... 적는 것..)
mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: mapper/*.xml
  # alias 설정
  type-aliases-package: com.ex.member.dto
